using System;
using System.Collections.Generic;
using System.Text;

namespace Solver.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class _002
    {
        public static Int32 Solve()
        {
            var sum = 0;
            var firstTerm = 0;
            var secondTerm = 1;
            var nextTerm = 0;
            
            while (nextTerm <= 4000000)
            {
                nextTerm = firstTerm + secondTerm;
                firstTerm = secondTerm;
                secondTerm = nextTerm;

                if (nextTerm % 2 == 0)
                {
                    sum = sum + nextTerm;
                }
            }

            return sum;
        }
    }
}
